{ pkgs, ... }:

let
  unstable = import
    (fetchTarball "https://github.com/NixOS/nixpkgs/archive/nixos-unstable.tar.gz")
    { config = pkgs.config; system = pkgs.stdenv.hostPlatform.system; };
in
{
  environment.systemPackages = with pkgs; [
    unstable.claude-code

    (btop.override { cudaSupport = true; })
    satty
    OVMF
    acpi
    asciiquarium
    bat
    bibata-cursors
    bottom
    brightnessctl
    btop
    busybox
    capitaine-cursors
    catfish
    cifs-utils
    clang-tools
    cloc
    cmake
    cowsay
    dig
    dunst
    eslint
    eslint_d
    expat
    eza
    fastfetch
    fd
    ffmpeg-full
    file
    flatpak
    fluidsynth
    flyctl
    fzf
    gcc
    gemini-cli
    gh
    gimp
    git
    glib
    gnumake
    gnumeric
    gnused
    go
    golangci-lint
    google-chrome
    gotools
    graphviz
    grim
    gst_all_1.gst-libav
    gst_all_1.gst-plugins-bad
    gst_all_1.gst-plugins-bad
    gst_all_1.gst-plugins-base
    gst_all_1.gst-plugins-good
    gst_all_1.gst-plugins-ugly
    gst_all_1.gstreamer
    hplip
    htop
    imagemagick
    jq
    kitty
    lazygit
    lemminx
    libde265
    libdrm
    libguestfs
    libnotify
    libreoffice-qt
    libva
    libva-vdpau-driver
    libvdpau
    lm_sensors
    minizip
    mpv
    ncdu
    nil
    nixd
    nixpkgs-fmt
    nodejs
    obs-studio
    odin
    ols
    onlyoffice-desktopeditors
    p7zip
    pamixer
    pavucontrol # Audio control panel
    pinta
    pkg-config
    prettier
    pulseaudio
    pwvucontrol # PipeWire volume control
    python3
    qsynth
    raylib
    rclone
    redshift
    ripgrep
    rofi
    slurp
    soundfont-fluid
    spice-gtk
    sqlite
    sqlitebrowser
    svelte-language-server
    swappy
    swaybg
    thunderbird
    typescript
    typescript-language-server
    ungoogled-chromium
    virt-manager
    vscode-langservers-extracted
    waybar
    wdisplays # GUI display configuration
    wget
    wine64
    wl-clipboard
    wl-mirror
    wofi
    wtype
    x265
    xclip
    xdotool
    xsel
    xwayland-satellite
    yazi
    zig
    zlib
    zoom-us
  ];
}
